print("Hello, World!")
print("What is your name? ")
name = input('>')
print("It is good to meet you, " + name)
print("The length of your name is: ")
print(len(name))
print("What is your age? ")
age = int(input('>'))
print("You will be " + str(age + 1) + " in a year.")